// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiuaicxjwcrunrvhzrnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpdWFpY3hqd2NydW5ydmh6cm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDUyNDcsImV4cCI6MjA3ODAyMTI0N30.caUHEZ2tI8kEd4g5R4mpag_vyd8yNXLT4YkPrih0M_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});